spring:
  profiles:
    active: dev
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1
    consumer:
      group-id: postman
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    topic:
      signal: trader.ctp.signal
      instrument: trader.ctp.instrument
app:
  ctp:
    ip: 180.168.146.187
    port: 10130
    broker-id: 9999
    app-id: simnow_client_test
    username: ENC(zKBo0JcnUim01LCH5Z9f9Q==)
    password: ENC(y6XhoIa5zT+XvXdjHMXmeA==)
    investor-id: ENC(kMaVQtJCACwzBKVRJi18kw==)
    account-id: ENC(10a/II0RKXDEJHAzLYJszA==)
    auth-code: ENC(inaGwoVJN/20FF8tDexDgBzsn6OM7ZNtL6VIRmAdWeE=)
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
