spring:
  profiles:
    active: dev
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:127.0.0.1:9092}
    producer:
      retries: 0
      # Config batch-size for better latency
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        linger.ms: 1
    consumer:
      group-id: trader-ctp
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    topic:
      trader:
        ctp:
          qry:
            instrument: trader.ctp.qry.instrument
            investor-position: trader.ctp.qry.investor-position
            trading-account: trader.ctp.qry.trading-account
            order: trader.ctp.qry.order
          order:
            insert: trader.ctp.order.insert
            action: trader.ctp.order.action
          rsp:
            instrument: trader.ctp.response.instrument
            investor-position: trader.ctp.response.investor-position
            trading-account: trader.ctp.response.trading-account
            order: trader.ctp.rsp.order
            trade: trader.ctp.rsp.trade
          rtn:
            order: trader.ctp.rtn.order
            trade: trader.ctp.rtn.trade
          err:
            order:
              insert: trader.ctp.err.order.insert
              action: trader.ctp.err.order.action
app:
  ctp:
    ip: 180.168.146.187
    port: 10130
    broker-id: 9999
    app-id: simnow_client_test
    username: ENC(zKBo0JcnUim01LCH5Z9f9Q==)
    password: ENC(y6XhoIa5zT+XvXdjHMXmeA==)
    investor-id: ENC(kMaVQtJCACwzBKVRJi18kw==)
    account-id: ENC(10a/II0RKXDEJHAzLYJszA==)
    auth-code: ENC(inaGwoVJN/20FF8tDexDgBzsn6OM7ZNtL6VIRmAdWeE=)
  trader:
    id: 1000
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
